0: unknownObj
60: person
32: bicycle
142: car
230: motorcycle
100: train
70: truckF
192: boat
101: bridge
1: buildingOtherMerged
181: gravel
140: railroad
128: road
96: pavementMerged
228: dirtMerged
124: sand
255: snow
108: floorOtherMerged
152: grassMerged
156: wallOtherMerged
143: rockMerged
149: waterOther
35: treeMerged
153: fenceMerged
180: skyOtherMerged
110: floorConcrete
28: container
38: selfArm
98: selfLeg
113: stone
141: gravelPile
84: sandPile
127: constructionMachine
129: bucket
130: gripper