0: unknownObj
1: person
2: bicycle
3: car
4: motorcycle
5: train
6: truck
7: boat
8: bridge
9: buildingOtherMerged
10: gravel
11: railroad
12: road
13: pavementMerged
14: dirtMerged
15: sand
16: snow
17: floorOtherMerged
18: grassMerged
19: wallOtherMerged
20: rockMerged
21: waterOther
22: treeMerged
23: fenceMerged
24: skyOtherMerged
25: floorConcrete
26: container
27: selfArm
28: selfLeg
29: stone
30: gravelPile
31: sandPile
32: constructionMachine
33: bucket
34: gripper
35: unknown
